version: "3"

services:
  ui:
    container_name: expense-tracker-ui
    build: ./ui
    volumes:
      - ./ui:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: ./api/.env.prod
    stdin_open: true

  api:
    container_name: expense-tracker-api
    restart: always
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file: ./api/.env.prod
    command: yarn dev

  mongo:
    container_name: expense-tracker-db
    image: mongo
    ports:
      - 27017:27017

volumes:
  node_modules:
